name: Pre-commit

on:
    push:
      branches: [ master, main ]
    pull_request:

jobs:
  check:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        shell: bash
        run: |
          make setup

      - name: Pre-commit hooks
        shell: bash
        run: |
          make pre-commit
